on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  chatgptComment:
    runs-on: ubuntu-latest
    name: Add Comment
    steps:
      - name: Add Comment 
        uses: jayS202/modified-pullrequest-summarizer@main
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          azure-api-key: ${{ secrets.AZURE_API_KEY }}
          azure-endpoint: ${{ secrets.AZURE_ENDPOINT }}
          max-prompt-tokens: '10000'
          ignore-paths: '.github/*, src/, package*.json, .env*'
          model: 'gpt-35'
          temperature: 1
          max-response-tokens: 512
          top_p: 1
          frequency-penalty: 0
          presence-penalty: 1
