on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  chatgptComment:
    runs-on: ubuntu-latest
    name: Add Comment
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
        with:
          repository: JayAshtkar/description-pullrequest-summarizer
          ref: main 
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Add Comment
        uses: JayAshtkar/description-pullrequest-summarizer@main
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          open-api-key: ${{ secrets.CHATGPT_API_KEY }}
          max-prompt-tokens: '10000'
          ignore-paths: '.github/*, src/, package*.json, .env*'
          model: 'gpt-35'
          temperature: 1
          max-response-tokens: 512
          top_p: 1
          frequency-penalty: 0
          presence-penalty: 1
